### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by dblandin**
This PR includes a few updates to the project's Dockerfile.

- Update base image to 8.6-alpine
- Quiet npm install output
- Gather advisories after npm install

### CODE REVIEW

**Comment by dblandin** [comment]
Not sure what to do regarding the build failure. Looks like other `3.0.0` branch builds are failing?

**Comment by nlf** [comment]
build failure isn't your fault :) thanks!

**Comment by dblandin** [comment]
@nlf Thanks for the merge! Is a v3.0 release still in progress? Any estimate on when the 3.0.0 branch will be merged into master?

**Comment by nlf** [comment]
I have one more feature to implement and then I’ll be merging it to master. It’s published to npm and is usable now though, you can npm install nsp@next to get it

**Comment by amitrai4code** [comment]
@nlf I am really waiting for the 3.0 release as it helps us setup our CI changes. Hope to see the update soon.

**Comment by nlf** [comment]
made 3.0 the master branch and published 3.1.0 just now

**Pull request merged**
