### PR TITLE
added advisoriesPath cmd line support

### PR DESCRIPTION
**Pull request by evilpacket**

### CODE REVIEW

**Comment by reedloden** [comment]
Also update in-line docs in `lib/check.js` like I did? https://github.com/nodesecurity/nsp/pull/64/files#diff-0e9a53fc6808cd403458fe3c3dfb431fL42

**Comment by reedloden** [comment]
and update `usage/check.txt`

**Comment by evilpacket** [comment]
@reedloden thanks, good catch. 

With our pull requests combined.

**Comment by evilpacket** [comment]
Should be done. Once @nlf gives it a quick look over I'll minor rev and publish

**Comment by nlf** [comment]
:+1: looks good to me

**Comment by reedloden** [comment]
Did you notice the spec failure on Node 0.10.x?

**Comment by reedloden** [comment]
Specifically https://drone.andyet.com/nodesecurity/nsp/15/1 (@evilpacket)

**Comment by evilpacket** [comment]
Yup, we are going to use a polyfill for isAbsolute before the push to maintain 0.10 support for now.

**Pull request merged**
