### PR TITLE
Export shared getFormatter() method for grunt-nsp module

### PR DESCRIPTION
**Pull request by pdehaan**
Ref: https://github.com/nodesecurity/grunt-nsp/issues/19

Saves having to copy-pasta that utility function to grunt-nsp and probably gulp-nsp.

### CODE REVIEW

**Comment by nlf** [comment]
good call! thanks @pdehaan

**Comment by pdehaan** [comment]
Not entirely related, but more of a side conversation, but I think we're also having some unexpected side effects from using shrinkwrap. In trying to debug this today, I realized that the package.json file uses some semver range operators so it looks like it would install [`"nsp": "^2.3.0"`](https://github.com/nodesecurity/grunt-nsp/blob/f623450225c314104b8edebb630f18ea48078522/package.json#L10), but because of the npm-shrinkwrap.json file, it will always only install exactly [`"version": "2.3.0"`](https://github.com/nodesecurity/grunt-nsp/blob/f623450225c314104b8edebb630f18ea48078522/npm-shrinkwrap.json#L6) &mdash; which means we'd have to regenerate the npm-shrinkwrap.json file every tiem we release a new version of **nsp**.

**Comment by nlf** [comment]
are you referring to your app that uses nsp? do you have it in your devDependencies?

**Comment by pdehaan** [comment]
@nlf, sorry, I was referring to the **grunt-nsp** module directly.

**Comment by nlf** [comment]
ah, then yes you're absolutely correct. since nsp is the _only_ dependency there though and it has its own shrinkwrap, i'll remove it from grunt-nsp. gulp-nsp only has one other dependency so i'll have to evaluate how i feel about removing the shrinkwrap there.

**Pull request merged**
