### PR TITLE
Add new warn-threshold option to configure the warning level

### PR DESCRIPTION
**Pull request by yannrouillard**
This a "pull request" proposition to fix the issue #130 that I raised.

### CODE REVIEW

**Comment by nlf** [comment]
again, very sorry for the delay in getting back to you on this. i love the idea here. i feel like some input validation would be good though, or at least a fallback threshold if an unknown string is passed in. right now invalid string inputs would cause the highest cvss score to be directly compared to the string itself, which will always equal `false` causing the warn threshold to basically be ignored.

**Comment by yannrouillard** [comment]
You are right, I will update the merge requests to take into account your comment.

**Comment by evilpacket** [comment]
@yannrouillard if you can address the comment by @nlf we can get this into the next release.

**Comment by nlf** [comment]
fixed in 3.0.0

**Pull request closed without merging**
