### PR TITLE
Add proxy to the gather command

### PR DESCRIPTION
**Pull request by eaviles**
This PR will make the "gather" use the proxy argument.

### CODE REVIEW

**Comment by eaviles** [comment]
@nlf for your consideration.

**Comment by v4x8182** [comment]
Thanks, this is working well!

**Review by bufferoverflow — APPROVED** [review]

**Comment by eaviles** [comment]
@bufferoverflow who can merge this? or what's the procedure?

**Comment by alexander-akait** [comment]
/cc @evilpacket @lynnandtonic @nlf @wraithgar
I want to thank for the great tool. To the bitterness, I began to notice that none of you communicate and react on issues and PRs are necessary for people. A security analysis tool is one of the main tool in any project. And I would like you to find time to maintain project. Thanks!

**Comment by nlf** [comment]
The Node Security Platform has been acquired by npm, Inc.
On April 10, 2018, the Node Security Platform joined npm, Inc., which operates the npm JavaScript package registry. 

[Learn more here.](https://medium.com/npm-inc/npm-acquires-lift-security-258e257ef639)

This service remains operational for current users in its current state. No new features or fixes will be implemented.

**Comment by alexander-akait** [comment]
@nlf i jown about this, what is official way to check your deps on insecurity packages right now? I can't found information about this, only works about `future` :confused:

**Pull request closed without merging**
