### PR TITLE
Add a --file option to make scripting easier

### PR DESCRIPTION
**Pull request by John-Steidley**

### CODE REVIEW

**Comment by evilpacket** [comment]
Seems like a good option to have. Mind throwing in a test for this and I'll merge it.

**Comment by John-Steidley** [comment]
All the tests right now are for the auditPackage function. Because this change operates outside of that function, it's difficult to test. Perhaps you could add other tests for the command line interface at a later time, but I don't really want to set up all of that test infrastructure just for this minor change.

**Comment by evilpacket** [comment]
Yeah that's true I guess. I was thinking there was more testing ha I should have realized. :) I'll get to this when I get to a computer.

**Comment by John-Steidley** [comment]
Great. Thanks for all your work!

**Comment by John-Steidley** [comment]
Just a reminder to hit merge when you get the chance. @evilpacket

**Comment by evilpacket** [comment]
I'll publish when I get a min. headed to bed atm, but can do tomorrow.

**Comment by John-Steidley** [comment]
@evilpacket, Any chance you'll get to this today?

**Comment by evilpacket** [comment]
Its merged will push tonight. Currently in the middle of no where.

**Comment by evilpacket** [comment]
@John-Steidley done, see 1.1.0

**Comment by John-Steidley** [comment]
Thank you very much.

**Pull request merged**
