### PR TITLE
Fix issue 166

### PR DESCRIPTION
**Pull request by jweinsteincbt**
Fix for issue #166 so it can download up to 99*100 advisories. Would be nice if api.nodesecurity.io did not have max limit of 100 advisories per request.

Does not have any new dependencies so should not require a new `npm shrinkwrap`.
Can re-write in es5 style instead of es6 if required.

### CODE REVIEW

**Comment by jweinsteincbt** [comment]
@nlf Do you want this in es5 style instead of es6?

**Comment by nlf** [comment]
my apologies, i've been heads down working on version 3.0 of the cli where i've made this a subcommand off of the actual tool. i have a 3.0.0 branch pushed that i'm working on tests and documentation for right now, plus a few more utility commands. you can see this functionality as `nsp gather` there

**Comment by jweinsteincbt** [comment]
Gave a quick look to the 3.0.0 branch
👍 can call it directly with `nsp gather` rather than needing to use `npm setup-offline`. Sweet! 🥇 

Couple of items you might want to think about before releasing 🙁 
* Changes format of advisories.json (okay since major release)
* Need to use later version of Node because of `..args` and other es6 features. You might consider adding: `"engines" : { "node" : ">=6.0.0" }` to your package.json
* Name `nsp gather` is a bit ambiguous ... perhaps rename to `nsp setup-offline` or just `nsp offline`?
* Might want to update error message: `Unable to load local advisories database` to include command you should run to download the advisories.json.

Feel free to close this PR. 
Let me know if you'd like me to submit a PR for any of the above items to the 3.0.0 branch.

**Comment by jweinsteincbt** [comment]
PS: You might want to update your Dockerfile to use new `nsp gather` command or have `npm run setup-offline` call `bin/nsp gather` in your package.json

**Comment by evilpacket** [comment]
I do agree with the gather command, we might want to rename it. I'll argue with nlf tomorrow. As for now I've submitted a couple commits with a few of your suggestions above.

**Pull request closed without merging**
