### PR TITLE
Add checkstyle formatter

### LINKED ISSUE #109: Add checkstyle formatter
To fully integrate nsp into our build system it would be beneficial if nsp supported checkstyle-compatible output.

### PR DESCRIPTION
**Pull request by pigulla**
Fixes #109

### CODE REVIEW

**Comment by evilpacket** [comment]
Thanks for the pull request. I'm curious what is checkstyle? I've never heard of it. What I saw with a quick search was http://checkstyle.sourceforge.net/ and a plugin for jenkins...

**Comment by pigulla** [comment]
As you probably saw, Checkstyle itself is a tool for validating Java coding styles and not particularly interesting in the Node.js world.

The output format that Checkstyle uses, however, is supported by many CI systems (Jenkins being one of them) and various tools in the JavaScript ecosystem, for instance [jscs](http://jscs.info/), [JSHint](http://jshint.com/) and [ESLint](http://eslint.org/) or [Complexity Report](https://github.com/escomplex/complexity-report). The point is that the CI can then aggregate the results of all of these tools and display the problems detected on a file-by-file basis (and let it handle whether the build should fail depending on the number of warnings and problems found).

Does this answer your question?

**Comment by pigulla** [comment]
Is there anything else I can do to help this PR go forward?

**Comment by pdehaan** [comment]
@pigulla Sorry, I think I derailed your PR with my dumb comments in #112.

I think there is a small bit of work to do here to support custom formatters on the **nsp** side, but the good news is that you could publish your custom "checkstyle" formatter to npm and manage it yourself without needing to land code in nsp.

**Comment by evilpacket** [comment]
Yes! Sorry for the delay. I think this would the best way to proceed. Any chance you could help us make this a better generic / plugin friendly solution for yourself and others?

**Comment by pigulla** [comment]
@evilpacket Yes, I can take a stab at it later this week :)

**Comment by pigulla** [comment]
Until then, let me close this PR since it doesn't look like it will be merged.

**Pull request closed without merging**
